---
stages:
- name: deploy
  inputs:
  - type: git
    branch: master
    service: ${SAMPLE_REPO}
  triggers:
  - type: commit
  properties:
  - name: CF_APP_NAME
    value: undefined
    type: text
  - name: APP_URL
    value: undefined
    type: text
  jobs:
  - name: FaaS Deploy
    type: deployer
    target:
      region_id: ${PROD_REGION_ID}
      organization: ${PROD_ORG_NAME}
      space: ${PROD_SPACE_NAME}
      application: ${CF_APP_NAME}
    script: |
      #!/bin/bash
      #bx plugin install cloud-functions -r Bluemix
      bx login -a https://api.ng.bluemix.net --apikey $APIKEY -o tmidboe@us.ibm.com -s dev
      bx wsk action invoke /whisk.system/utils/echo -p message hello --blocking --result
      # now set up your actions etc
      bx wsk action update action1 --kind nodejs:8 actions/action1.js
      # check everything is as expected
      bx wsk action list
      
