---
stages:
- name: deploy
  inputs:
  - type: git
    branch: master
    service: ${SAMPLE_REPO}
  triggers:
  - type: commit
  properties:
  - name: CF_APP_NAME
    value: undefined
    type: text
  - name: APP_URL
    value: undefined
    type: text
  - name: API_KEY
    type: text
    value: ${API_KEY}
  jobs:
  - name: FaaS Deploy
    type: deployer
    target:
      region_id: ${PROD_REGION_ID}
      organization: ${PROD_ORG_NAME}
      space: ${PROD_SPACE_NAME}
      application: ${CF_APP_NAME}
      api_key: ${API_KEY}
    script: |
      #!/bin/bash
      echo "API_KEY=${API_KEY}"
      echo "PROD_REGION_ID=${PROD_REGION_ID}"
      echo "PROD_SPACE_NAME=${PROD_SPACE_NAME}"
      bx login -a https://api.ng.bluemix.net --apikey ${API_KEY} -o tmidboe@us.ibm.com -s dev
      bx wsk action invoke /whisk.system/utils/echo -p message hello --blocking --result
      # now set up your actions etc
      for i in `find actions -type f \( -name "*.js" -or -name "*.py" \)` ; do
        file=`echo $i | cut -d "/" -f 2`
        type=`echo $file | cut -d "." -f 2`
        name=`echo $file | cut -d "." -f 1`
        if [ $type == "js" ] ; then
          kind="nodejs:8"
        else
          kind="python:3"
        fi
        bx wsk action update $name --kind $kind $i
      done 
      # check everything is as expected
      bx wsk action list
      
